language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: pat-farrell-17-github
    token:
      secure: 1f9bc10653fdcfa412b4d545647833ff05b7fc91
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'